### ISSUE TITLE
useConstraints and useLimitation not created

### ISSUE THREAD

**Issue by juliepierson** [eblondel/geoflow#119]
Hi,
In "Rights" column of csv I have this :
`useLimitation:Utilisation libre sous réserve de mentionner la source_`
`accessConstraint:otherRestrictions_`
`useConstraints:intellectualPropertyRights_`
`otherConstraint:Le fournisseur n’est pas en mesure de garantir l’exactitude`
But in metadata only accessConstraints and otherConstraints get created, not useLimitation nor useConstraints.
Thanks for your help once again !

**Comment by eblondel** [comment]
geoflow is mapped to, and inspired by ISO 19115, but not only. For this, documentation is ongoing to show which keys to use:
* ``use`` instead of ``useLimitation`` and it will work
* ``useConstraint`` (not plural) and it will work
All this was drafted quickly to make sure that we can have these elements in ISO 19115, but since there is an ongoing documentation process, i'm open to refine the keys that should match to ISO 19115 useLimitation, access/use/other constraints, if they are better proposals. For this we need to look into other metadata standards that are used and managed by geoflow, such as EML, dataverse, zenodo,

**Comment by juliepierson** [comment]
It works, thanks !! We used useLimitation and useConstraints because that's how they appear in the XML, but as long as the terms to use in csv are documented, it's ok for me.
