### ISSUE TITLE
Links to parent resource not shown in GN

### ISSUE THREAD

**Issue by mathieu-massaviol** [eblondel/geoflow#223]
The link to a parent dataset is not shown in the Geonetwork.

**Comment by eblondel** [comment]
Can you share the geonetwork metadata link? (is it public?)

**Comment by mathieu-massaviol** [comment]
@EmilieLerigoleur Do you have the geonetwork metadata link to this error ? I dont have it.

**Comment by eblondel** [comment]
Hum, it shows up, under "Associated Resources" (Ressources associées), I get the parent metadata listed.

**Comment by EmilieLerigoleur** [comment]
Yes but it is not clear that this is the parent metadata file (whereas in Geonetwork it is clearly identified)

**Comment by eblondel** [comment]
I'm not sure to understand the requirement. In Geonetwork, It says "Fiche parent" at top right of the "associated resource" box. In any case, for the UI, this is more an issue of Geonetwork UI. For the ISO 19115/19139, it is coded as parentIdentifier, that's the way the ISO standards defines it.
Do you mean that what is not clear is the "parent" key for your entity table? too implicit?

**Comment by EmilieLerigoleur** [comment]
Here is the result after executing geoflow for a metadata file which contains a parent metadata URL. In dataverse the "Related Material" contains : RZA metacatalog metadata: http://meta.data-za.org/geonetwork/srv/fre/catalog.search#/metadata/3719ff01-0c62-4596-a7d1-c8487c798444; ea665b7d-80b5-4da8-a18a-f02c524c0dee: http://meta.data-za.org/geonetwork/srv/fre/catalog.search#/metadata/ea665b7d-80b5-4da8-a18a-f02c524c0dee
That is incomprehensible!
Problems are: 
1) no line breaks between URLs 
2) the second URL is the parent metadata file but there is no information mentioning it.

**Comment by eblondel** [comment]
Ah ok, so we talk about dataverse, :-) not GN! Here's the misunderstanding
Dataverse is quite poor in term of rendering, and more, its limited support to Dublin Core XML / SWORD API made me take some choice in order to display the resource set as relation (otherwise it would have been totally useless). For that geoflow adds as many relations as we have in the column "Relation", and does a concatenation with the name of the resource followed by its URL https://github.com/eblondel/geoflow/blob/master/R/geoflow_action_atom4R_dataverse_deposit_record.R#L118 I agree that is it not the best way to do it, but given the Dataverse limitations, that was a starting point.
What I suggest:
* for the parent: we remove the 'parent' relation from the dataverse action, it would be used only for ISO 19115/geonetwork.
* I keep investigating if we can pass URIs (eg. through xml xlink:href attribute) to the Dublin Core XML object, crossing fingers that it is managed by Dataverse (I doubt sincerely)
Let me know

**Comment by EmilieLerigoleur** [comment]
Thank you!
Is there any possibility to add the fixed text "Parent metadata file URI" before the URI of the parent metadata file in the Dataverse "Related Material" field? if not ok to remove the parent relation from the dataverse action.

**Comment by eblondel** [comment]
Have you tried this?

http:RZA metacatalog metadata@http://meta.data-za.org/geonetwork/srv/fre/catalog.search#/metadata/3719ff01-0c62-4596-a7d1-c8487c798444_
parent:Parent metadata file URI@http://meta.data-za.org/geonetwork/srv/fre/catalog.search#/metadata/ea665b7d-80b5-4da8-a18a-f02c524c0dee


Based on the following syntax ``name[description]@uri``, the output in dataverse will be:
* if you put a description: ` name: description - uri`
* if you don't put a description (your case): ``name: uri``

The code for the dataverse action can be improved but so far this is what it does. 

Unfortunately Dataverse takes these relations and paste them all together. We can't do anything for that. We could improve the way name/description/uri and pasted together, but still the result will be a text in Dataverse;
